Traceback (most recent call last):
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bhills/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bhills/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np

import sys
sys.path.insert(1, '../squintsar/lib/')
from sar_geometry import *
from sar_functions import *
from supplemental import *
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      5[0m sys[38;5;241m.[39mpath[38;5;241m.[39minsert([38;5;241m1[39m, [38;5;124m'[39m[38;5;124m../squintsar/lib/[39m[38;5;124m'[39m)
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01msar_geometry[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01msar_functions[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01msupplemental[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

[0;31mModuleNotFoundError[0m: No module named 'sar_functions'

